Rottenwood\UtopiaMudBundle\Entity\Player:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
#        - Callback:
#            methods:
#                - [Rottenwood\UtopiaMudBundle\Validator\Validator, isEmailValid]
    properties:
        email:
            - Email: ~
        username:
            - Regex:
                pattern: "/\d/"
                match:   false
                message: Your name cannot contain a number