<?php

namespace Rottenwood\UtopiaMudBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MobitemRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MobitemRepository extends EntityRepository {

}
