<?php

namespace Rottenwood\UtopiaMudBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MobRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MobRepository extends EntityRepository {

}
