<?php

namespace Rottenwood\UtopiaMudBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository {

    public function findAllOrderedByName() {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM RottenwoodUtopiaMudBundle:Player p ORDER BY p.name ASC')
            ->getResult();
    }
}
