<?php

namespace Rottenwood\UtopiaMudBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoomRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends EntityRepository {

    public function findCurrentRoom($id) {

        $query = $this->getEntityManager()->createQuery('SELECT r FROM RottenwoodUtopiaMudBundle:Room r WHERE r.id LIKE
        :id');
        $query->setParameter('id', '%' . $id . '%');
        $result = $query->getResult();

        return $result;
    }
}
