parameters:
#    rottenwood_user.example.class: Rottenwood\UserBundle\Example

services:
#    rottenwood_user.example:
#        class: %rottenwood_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
